name: tsukina.ga/leo

title: tsukina.ga/leo
description: "&quot;In this transient world, as agonizing as the third circle of hell, what binds us together is music! Music is the shared language of the world!&quot;"

version: v0.2

baseurl: ""
permalink: /leo/
logo: /assets/logo.png

theme: minima

minima:
  skin: dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: junsweats
    github:  jeaoq

header_pages:
    - about.md


show_excerpts: true # set to true to show excerpts on the homepage


plugins:
 - jekyll-redirect-from
 - jekyll-feed
 - jekyll-seo-tag

collections:
  urls:
    output: true
    permalink: /:slug

whitelist:
  - jekyll-redirect-from

redirect_from:
  json: false

include:
  - _urls
  - _posts

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: tsukinagaleo

url: https://tsukina.ga
